-- ═══════════════════════════════════════════════════════════════════════════════════════
-- 📋 UPDATE PASSWORD HASH FOR TEST USERS
-- Purpose: แก้ไข BCrypt hash ให้เป็นค่าจริงสำหรับ password "P@ssw0rd123"
--
-- 📅 Created: 2025-12-17
-- 🔐 Hash generated by: BCrypt.Net.BCrypt.HashPassword("P@ssw0rd123", 12)
-- ═══════════════════════════════════════════════════════════════════════════════════════

-- ✅ CORRECT BCrypt hash for "P@ssw0rd123"
UPDATE dbo.HRB_USER
SET PasswordHash = '$2a$12$LO29NAv8mlT.MN6yZtC7JeS.uImYqgfRP46HBhLfoUMN8Ohe2nR/2'
WHERE AuthType = 'DB';

-- Verify update
SELECT
    UserId,
    Username,
    LEFT(PasswordHash, 30) + '...' AS PasswordHashPreview,
    Role
FROM dbo.HRB_USER
WHERE AuthType = 'DB';
