-- ═══════════════════════════════════════════════════════
-- PE Notification System Migration Script
-- Created: December 12, 2025
-- Version: 1.0
-- ═══════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════
-- 1. Create HRB_PE_NOTIFICATION Table
-- ═══════════════════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_NOTIFICATION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [HRBUDGET].[HRB_PE_NOTIFICATION] (
        [NOTIFICATION_ID] INT IDENTITY(1,1) NOT NULL,
        [MOVEMENT_ID] INT NOT NULL,
        [NOTIFICATION_TYPE] NVARCHAR(50) NOT NULL,
        [NOTIFICATION_CATEGORY] NVARCHAR(50) NOT NULL,
        [RECIPIENT_EMP_CODE] NVARCHAR(100) NOT NULL,
        [RECIPIENT_COST_CENTER] NVARCHAR(50) NULL,
        [SENDER_EMP_CODE] NVARCHAR(100) NOT NULL,
        [SENDER_COST_CENTER] NVARCHAR(50) NULL,
        [TITLE] NVARCHAR(200) NOT NULL,
        [MESSAGE] NVARCHAR(1000) NULL,
        [HC] INT NOT NULL DEFAULT 0,
        [BASE_WAGE] DECIMAL(18,2) NOT NULL DEFAULT 0,
        [PE_MONTH] INT NOT NULL,
        [PE_YEAR] INT NOT NULL,
        [COMPANY_ID] INT NOT NULL,
        [ACTION_URL] NVARCHAR(500) NULL,
        [ACTION_DATA] NVARCHAR(MAX) NULL,
        [EMAIL_LOG_ID] INT NULL,
        [EMAIL_SENT] BIT NOT NULL DEFAULT 0,
        [EMAIL_SENT_DATE] DATETIME NULL,
        [HAS_ATTACHMENT] BIT NOT NULL DEFAULT 0,
        [UPLOAD_LOG_ID] INT NULL,
        [IS_READ] BIT NOT NULL DEFAULT 0,
        [READ_DATE] DATETIME NULL,
        [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
        [CREATED_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
        [CREATED_BY] NVARCHAR(100) NULL,
        CONSTRAINT [PK_HRB_PE_NOTIFICATION] PRIMARY KEY CLUSTERED ([NOTIFICATION_ID] ASC)
    );

    PRINT 'Created table HRB_PE_NOTIFICATION';
END
ELSE
BEGIN
    PRINT 'Table HRB_PE_NOTIFICATION already exists';
END
GO

-- Create Indexes for HRB_PE_NOTIFICATION
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_PE_NOTIFICATION_Recipient' AND object_id = OBJECT_ID('HRBUDGET.HRB_PE_NOTIFICATION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_PE_NOTIFICATION_Recipient]
    ON [HRBUDGET].[HRB_PE_NOTIFICATION] ([RECIPIENT_EMP_CODE], [IS_READ], [IS_ACTIVE]);
    PRINT 'Created index IX_HRB_PE_NOTIFICATION_Recipient';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_PE_NOTIFICATION_Movement' AND object_id = OBJECT_ID('HRBUDGET.HRB_PE_NOTIFICATION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_PE_NOTIFICATION_Movement]
    ON [HRBUDGET].[HRB_PE_NOTIFICATION] ([MOVEMENT_ID]);
    PRINT 'Created index IX_HRB_PE_NOTIFICATION_Movement';
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_PE_NOTIFICATION_Category' AND object_id = OBJECT_ID('HRBUDGET.HRB_PE_NOTIFICATION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_PE_NOTIFICATION_Category]
    ON [HRBUDGET].[HRB_PE_NOTIFICATION] ([NOTIFICATION_CATEGORY], [CREATED_DATE] DESC);
    PRINT 'Created index IX_HRB_PE_NOTIFICATION_Category';
END
GO

-- ═══════════════════════════════════════════════════════
-- 2. Add Approval Fields to HRB_PE_MOVEMENT
-- ═══════════════════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'APPROVAL_STATUS')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [APPROVAL_STATUS] NVARCHAR(50) NULL;
    PRINT 'Added column APPROVAL_STATUS to HRB_PE_MOVEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'REQUIRES_APPROVAL')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [REQUIRES_APPROVAL] BIT NOT NULL DEFAULT 0;
    PRINT 'Added column REQUIRES_APPROVAL to HRB_PE_MOVEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'PENDING_COST_CENTER')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [PENDING_COST_CENTER] NVARCHAR(50) NULL;
    PRINT 'Added column PENDING_COST_CENTER to HRB_PE_MOVEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'PENDING_EMP_CODE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [PENDING_EMP_CODE] NVARCHAR(100) NULL;
    PRINT 'Added column PENDING_EMP_CODE to HRB_PE_MOVEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'REJECTED_REASON')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [REJECTED_REASON] NVARCHAR(500) NULL;
    PRINT 'Added column REJECTED_REASON to HRB_PE_MOVEMENT';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_PE_MOVEMENT]') AND name = 'UPLOAD_LOG_ID')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_PE_MOVEMENT] ADD [UPLOAD_LOG_ID] INT NULL;
    PRINT 'Added column UPLOAD_LOG_ID to HRB_PE_MOVEMENT';
END
GO

-- Create Index for pending approvals
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_PE_MOVEMENT_Pending' AND object_id = OBJECT_ID('HRBUDGET.HRB_PE_MOVEMENT'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_PE_MOVEMENT_Pending]
    ON [HRBUDGET].[HRB_PE_MOVEMENT] ([PENDING_EMP_CODE], [APPROVAL_STATUS])
    WHERE [REQUIRES_APPROVAL] = 1;
    PRINT 'Created index IX_HRB_PE_MOVEMENT_Pending';
END
GO

-- ═══════════════════════════════════════════════════════
-- 3. Add Reference Fields to HRB_EMAIL_LOG
-- ═══════════════════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_EMAIL_LOG]') AND name = 'REF_TYPE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_EMAIL_LOG] ADD [REF_TYPE] NVARCHAR(50) NULL;
    PRINT 'Added column REF_TYPE to HRB_EMAIL_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_EMAIL_LOG]') AND name = 'REF_ID')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_EMAIL_LOG] ADD [REF_ID] INT NULL;
    PRINT 'Added column REF_ID to HRB_EMAIL_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_EMAIL_LOG]') AND name = 'TEMPLATE_CODE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_EMAIL_LOG] ADD [TEMPLATE_CODE] NVARCHAR(50) NULL;
    PRINT 'Added column TEMPLATE_CODE to HRB_EMAIL_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_EMAIL_LOG]') AND name = 'RETRY_COUNT')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_EMAIL_LOG] ADD [RETRY_COUNT] INT NOT NULL DEFAULT 0;
    PRINT 'Added column RETRY_COUNT to HRB_EMAIL_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_EMAIL_LOG]') AND name = 'MAX_RETRY')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_EMAIL_LOG] ADD [MAX_RETRY] INT NOT NULL DEFAULT 3;
    PRINT 'Added column MAX_RETRY to HRB_EMAIL_LOG';
END
GO

-- Create Index for HRB_EMAIL_LOG
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_EMAIL_LOG_Ref' AND object_id = OBJECT_ID('HRBUDGET.HRB_EMAIL_LOG'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_EMAIL_LOG_Ref]
    ON [HRBUDGET].[HRB_EMAIL_LOG] ([REF_TYPE], [REF_ID]);
    PRINT 'Created index IX_HRB_EMAIL_LOG_Ref';
END
GO

-- ═══════════════════════════════════════════════════════
-- 4. Add Reference Fields to HRB_UPLOAD_LOG
-- ═══════════════════════════════════════════════════════

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_UPLOAD_LOG]') AND name = 'REF_TYPE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_UPLOAD_LOG] ADD [REF_TYPE] NVARCHAR(50) NULL;
    PRINT 'Added column REF_TYPE to HRB_UPLOAD_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_UPLOAD_LOG]') AND name = 'REF_ID')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_UPLOAD_LOG] ADD [REF_ID] INT NULL;
    PRINT 'Added column REF_ID to HRB_UPLOAD_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_UPLOAD_LOG]') AND name = 'FILE_TYPE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_UPLOAD_LOG] ADD [FILE_TYPE] NVARCHAR(50) NULL;
    PRINT 'Added column FILE_TYPE to HRB_UPLOAD_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_UPLOAD_LOG]') AND name = 'MIME_TYPE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_UPLOAD_LOG] ADD [MIME_TYPE] NVARCHAR(100) NULL;
    PRINT 'Added column MIME_TYPE to HRB_UPLOAD_LOG';
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[HRBUDGET].[HRB_UPLOAD_LOG]') AND name = 'IS_ACTIVE')
BEGIN
    ALTER TABLE [HRBUDGET].[HRB_UPLOAD_LOG] ADD [IS_ACTIVE] BIT NOT NULL DEFAULT 1;
    PRINT 'Added column IS_ACTIVE to HRB_UPLOAD_LOG';
END
GO

-- Create Index for HRB_UPLOAD_LOG
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HRB_UPLOAD_LOG_Ref' AND object_id = OBJECT_ID('HRBUDGET.HRB_UPLOAD_LOG'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_HRB_UPLOAD_LOG_Ref]
    ON [HRBUDGET].[HRB_UPLOAD_LOG] ([REF_TYPE], [REF_ID]);
    PRINT 'Created index IX_HRB_UPLOAD_LOG_Ref';
END
GO

-- ═══════════════════════════════════════════════════════
-- 5. Verify Migration
-- ═══════════════════════════════════════════════════════

PRINT '';
PRINT '═══════════════════════════════════════════════════════';
PRINT '✅ PE Notification System Migration Completed!';
PRINT '═══════════════════════════════════════════════════════';
PRINT '';
PRINT 'Tables Created/Modified:';
PRINT '  • HRB_PE_NOTIFICATION (NEW)';
PRINT '  • HRB_PE_MOVEMENT (6 new columns)';
PRINT '  • HRB_EMAIL_LOG (5 new columns)';
PRINT '  • HRB_UPLOAD_LOG (5 new columns)';
PRINT '';
PRINT 'Indexes Created:';
PRINT '  • IX_HRB_PE_NOTIFICATION_Recipient';
PRINT '  • IX_HRB_PE_NOTIFICATION_Movement';
PRINT '  • IX_HRB_PE_NOTIFICATION_Category';
PRINT '  • IX_HRB_PE_MOVEMENT_Pending';
PRINT '  • IX_HRB_EMAIL_LOG_Ref';
PRINT '  • IX_HRB_UPLOAD_LOG_Ref';
GO
